#include "../lib/my.h"

int main(void)
{
  char *p;
  char str[128] = "life is great!";

  my_str("\nmy_strcpy()\n-----------\n");
  my_str("original str = ");
  my_str(str);
  my_char('\n');
  my_str("my_strcpy(NULL, NULL) = ");
  my_str(my_strcpy(NULL, NULL));
  my_char('\n');
  my_str("my_strcpy(str, \"hello\") = ");
  my_str(my_strcpy(str, "hello"));
  my_char('\n');
  my_strcpy(str, "life is great!");
  my_str("str is \"life is great!\" again...\n");
  my_str("my_strcpy(str, NULL) = ");
  my_str(my_strcpy(str, NULL));
  my_char('\n');
  my_str("my_strcpy(NULL, \"hello\") = ");
  my_str(my_strcpy(NULL, "hello"));
  my_char('\n');
  my_str("my_strcpy(str, \"h\") = ");
  my_str(my_strcpy(str, "h"));
  my_str("\n\n");

  my_str("my_strdup()\n-----------\n");
  my_str("my_strdup(\"hello\\n\") = ");
  my_str(p = my_strdup("hello\n"));
  free(p);
  my_str("my_strdup(NULL) = ");
  my_str(p = my_strdup(NULL));
  /* can't free a NULL pointer */
  my_str("\n\n");

  my_str("my_find()\n---------\n");
  my_str("my_find(\"hello\", 'e') = ");
  my_char(*my_find("hello", 'e'));
  my_char('\n');
  my_str("my_find(\"hello\", 'h') = ");
  my_char(*my_find("hello", 'h'));
  my_char('\n');
  my_str("my_find(\"hello\", 'o') = ");
  my_char(*my_find("hello", 'o'));
  my_char('\n');
  my_str("my_find(\"hello\", 'H') = ");
  p = my_find("hello", 'H');
  if (p) my_char(*p);
  my_char('\n');
  my_str("my_find(NULL, 'h') = ");
  p = my_find(NULL, 'h');
  if (p) my_char(*p);
  my_str("\n\n");

  my_str("my_rfind()\n----------\n");
  my_str("my_rfind(\"hello\", 'e') = ");
  my_char(*my_rfind("hello", 'e'));
  my_char('\n');
  my_str("my_rfind(\"hello\", 'h') = ");
  my_char(*my_rfind("hello", 'h'));
  my_char('\n');
  my_str("my_rfind(\"hello\", 'o') = ");
  my_char(*my_rfind("hello", 'o'));
  my_char('\n');
  my_str("my_rfind(\"hello\", 'H') = ");
  p = my_rfind("hello", 'H');
  if (p) my_char(*p);
  my_char('\n');
  my_str("my_rfind(NULL, 'h') = ");
  p = my_rfind(NULL, 'h');
  if (p) my_char(*p);
  my_str("\n\n");

  my_str("my_strcat()\n-----------\n");
  my_strcpy(str, "life is great!");
  my_str("original str = ");
  my_str(str);
  my_char('\n');  my_char('\n');/*bbbb*/ my_char('\n');/*bbbb*/
  my_str("my_strcat(str, \" and beautiful!\") = ");
  my_str(my_strcat(str, " and beautiful!"));
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_strcat(str, \"!\") = ");
  my_str(my_strcat(str, "!"));
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_strcat(str, \"\") = ");
  my_str(my_strcat(str, ""));
  my_char('\n');
  my_str("my_strcat(NULL, NULL) = ");
  my_str(my_strcat(NULL, NULL));
  my_char('\n');
  my_str("my_strcat(str, NULL) = ");
  my_str(my_strcat(str, NULL));
  my_char('\n');
  my_str("my_strcat(NULL, \"!\") = ");
  my_str(my_strcat(NULL, "!"));
  my_str("\n\n");

  my_str("my_strcmp()\n-----------\n");
  my_str("my_strcmp(NULL, NULL) = ");
  my_int(my_strcmp(NULL, NULL));
  my_char('\n');
  my_str("my_strcmp(\"abc\", \"abc\") = ");
  my_int(my_strcmp("abc", "abc"));
  my_char('\n');
  my_str("my_strcmp(\"a\", \"abc\") = ");
  my_int(my_strcmp("a", "abc"));
  my_char('\n');
  my_str("my_strcmp(\"abc\", \"a\") = ");
  my_int(my_strcmp("abc", "a"));
  my_char('\n');
  my_str("my_strcmp(\"a\", \"a\") = ");
  my_int(my_strcmp("a", "a"));
  my_char('\n');
  my_str("my_strcmp(\"abc\", \"abcd\") = ");
  my_int(my_strcmp("abc", "abcd"));
  my_char('\n');
  my_str("my_strcmp(\"abcd\", \"abc\") = ");
  my_int(my_strcmp("abcd", "abc"));
  my_char('\n');
  my_str("my_strcmp(NULL, \"abc\") = ");
  my_int(my_strcmp(NULL, "abc"));
  my_char('\n');
  my_str("my_strcmp(\"abc\", NULL) = ");
  my_int(my_strcmp("abc", NULL));
  my_char('\n');
  my_str("my_strcmp(\"\", \"a\") = ");
  my_int(my_strcmp("", "a"));
  my_char('\n');
  my_str("my_strcmp(\"a\", \"\") = ");
  my_int(my_strcmp("a", ""));
  my_str("\n\n");

  my_str("my_strncmp()\n------------\n");
  my_str("my_strncmp(NULL, NULL) = ");
  my_int(my_strncmp(NULL, NULL, 5));
  my_char('\n');
  my_str("my_strncmp(\"abc\", \"abd\", 3) = ");
  my_int(my_strncmp("abc", "abd", 3));
  my_char('\n');
  my_str("my_strncmp(\"abd\", \"abc\", 3) = ");
  my_int(my_strncmp("abd", "abc", 3));
  my_char('\n');
  my_str("my_strncmp(\"abc\", \"abd\", 2) = ");
  my_int(my_strncmp("abc", "abd", 2));
  my_char('\n');
  my_str("my_strncmp(\"abc\", \"abd\", 1) = ");
  my_int(my_strncmp("abc", "abd", 1));
  my_char('\n');
  my_str("my_strncmp(\"a\", \"abc\", 5) = ");
  my_int(my_strncmp("a", "abc", 5));
  my_char('\n');
  my_str("my_strncmp(NULL, \"abc\", 2) = ");
  my_int(my_strncmp(NULL, "abc", 2));
  my_char('\n');
  my_str("my_strncmp(\"abc\", NULL, 1) = ");
  my_int(my_strncmp("abc", NULL, 1));
  my_char('\n');
  my_str("my_strncmp(\"\", \"a\", 20) = ");
  my_int(my_strncmp("", "a", 20));
  my_char('\n');
  my_str("my_strncmp(\"a\", \"\", 3) = ");
  my_int(my_strncmp("a", "", 3));
  my_char('\n');
  my_str("my_strncmp(\"a\", \"\", 0) = ");
  my_int(my_strncmp("a", "", 0));
  my_char('\n');
  my_str("my_strncmp(\"a\", \"abc\", -5) = ");
  my_int(my_strncmp("a", "abc", -5));
  my_str("\n\n");

  my_str("my_strconcat()\n--------------\n");
  my_strcpy(str, "life is great!");
  my_str("original str = ");
  my_str(str);
  my_char('\n');
  my_str("my_strconcat(str, \" and beautiful!\") = ");
  my_str(p = my_strconcat(str, " and beautiful!"));
  free(p);
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_strconcat(str, \"!\") = ");
  my_str(p = my_strconcat(str, "!"));
  free(p);
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_strconcat(str, \"\") = ");
  my_str(p = my_strconcat(str, ""));
  free(p);
  my_char('\n');
  my_str("my_strconcat(NULL, NULL) = ");
  my_str(p = my_strconcat(NULL, NULL));
  my_char('\n');
  /* can't free NULL pointer */
  my_str("my_strconcat(str, NULL) = ");
  my_str(p = my_strconcat(str, NULL));
  free(p);
  my_char('\n');
  my_str("my_strconcat(NULL, \"!\") = ");
  my_str(p = my_strconcat(NULL, "!"));
  free(p);
  my_str("\n\n");

  my_str("my_strnconcat()\n---------------\n");
  my_strcpy(str, "life is great!");
  my_str("original str = ");
  my_str(str);
  my_char('\n');
  my_str("my_strnconcat(str, \" and beautiful!\", my_strlen(\" and beautiful!\")) = ");
  my_str(p = my_strnconcat(str, " and beautiful!", my_strlen(" and beautiful!")));
  free(p);
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_strnconcat(str, \" and beautiful!\", 6) = ");
  p = my_strnconcat(str, " and beautiful", 6);
  *(p + my_strlen(str) + my_strlen(" and b")) = '\0';
  my_str(p);
  free(p);
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_strnconcat(str, \"\", 1) = ");
  p = my_strnconcat(str, "", 1);
  *(p + my_strlen(str) + my_strlen("")) = '\0';
  my_str(p);
  free(p);
  my_char('\n');
  my_str("my_strnconcat(NULL, NULL, 4) = ");
  my_str(p = my_strnconcat(NULL, NULL, 4));
  my_char('\n');
  /* can't free NULL pointer */
  my_str("my_strnconcat(str, NULL) = ");
  p = my_strnconcat(str, NULL, 1);
  my_str(p);
  free(p);
  my_char('\n');
  my_str("my_strnconcat(NULL, \"!\", 7) = ");
  my_str(p = my_strnconcat(NULL, "!", 7));
  free(p);
  my_char('\n');
  my_str("my_strnconcat(\"hello\", \"world\", -5) = ");
  p = my_strnconcat("hello", "world", -5);
  my_str(p);
  free(p);
  my_str("\n\n");

  my_str("my_stdstrnconcat()\n------------------\n");
  my_strcpy(str, "life is great!");
  my_str("original str = ");
  my_str(str);
  my_char('\n');
  my_str("my_stdstrnconcat(str, \" and beautiful!\", my_strlen(\" and beautiful!\")) = ");
  my_str(p = my_stdstrnconcat(str, " and beautiful!", my_strlen(" and beautiful!")));
  free(p);
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_stdstrnconcat(str, \" and beautiful!\", 6) = ");
  p = my_stdstrnconcat(str, " and beautiful", 6);
  *(p + my_strlen(str) + my_strlen(" and b")) = '\0';
  my_str(p);
  free(p);
  my_strcpy(str, "life is great!");
  my_str("\nstr is \"life is great!\" again...\n");
  my_str("my_stdstrnconcat(str, \"\", 1) = ");
  p = my_strnconcat(str, "", 1);
  /**(p + my_strlen(str) + my_strlen("")) = '\0';*/
  my_str(p);
  /*free(p);*/
  my_char('\n');
  my_str("my_stdstrnconcat(NULL, NULL, 4) = ");
  my_str(p = my_stdstrnconcat(NULL, NULL, 4));
  my_char('\n');
  /* can't free NULL pointer */
  my_str("my_stdstrnconcat(str, NULL) = ");
  p = my_stdstrnconcat(str, NULL, 1);
  my_str(p);
  free(p);
  my_char('\n');
  my_str("my_stdstrnconcat(NULL, \"!\", 7) = ");
  my_str(p = my_stdstrnconcat(NULL, "!", 7));
  /*free(p);*/
  my_char('\n');
  my_str("my_stdstrnconcat(\"hello\", \"world\", -5) = ");
  p = my_stdstrnconcat("hello", "world", -5);
  my_str(p);
  free(p);
  my_str("\n\n");

  my_str("my_strncpy()\n------------\n");
  my_str("I don't need to test my_strncpy() directly because ");
  my_str("I call it inside other functions that seem to ");
  my_str("be working the way they should.\n\n");

  /*my_str("\nmy_char()\n---------\n");
  my_str("my_char(' ') = ");
  my_char(' ');
  my_char('\n');
  my_str("my_char('a') = ");
  my_char('a');
  my_char('\n');
  my_str("my_char('e') = ");
  my_char('e');
  my_char('\n');
  my_str("my_char('.') = ");
  my_char('.');
  my_char('\n');

  my_str("\nmy_str()\n--------\n");
  my_str("my_str(\"\") = ");
  my_str("");
  my_char('\n');
  my_str("my_str(\"hello\\n\") = ");
  my_str("hello\n");
  my_str("my_str(\"123\\n\") = ");
  my_str("123\n");
  my_str("my_str(NULL) = ");
  my_str(NULL);
  my_char('\n');

  my_str("\nmy_int()\n--------\n");
  my_str("my_int(-1234) = ");
  my_int(-1234);
  my_char('\n');
  my_str("my_int(-123) = ");
  my_int(-123);
  my_char('\n');
  my_str("my_int(12) = ");
  my_int(12);
  my_char('\n');
  my_str("my_int(1) = ");
  my_int(1);
  my_char('\n');
  my_str("my_int(0) = ");
  my_int(0);
  my_char('\n');

  my_str("\nmy_alpha()\n----------\n");
  my_alpha();
  my_char('\n');

  my_str("\nmy_digits()\n-----------\n");
  my_digits();
  my_char('\n');

  my_str("\nmy_strlen()\n-----------\n");
  my_str("my_strlen(\"hello\") = ");
  my_int(my_strlen("hello"));
  my_char('\n');
  my_str("my_strlen(\"\") = ");
  my_int(my_strlen(""));
  my_char('\n');
  my_str("my_strlen(NULL) = ");
  my_int(my_strlen(NULL));
  my_char('\n');
  my_str("my_strlen(\"a\") = ");
  my_int(my_strlen("a"));
  my_char('\n');

  my_str("\nmy_strindex()\n-------------\n");
  my_str("my_strindex(\"hello\", 'l') = ");
  my_int(my_strindex("hello", 'l'));
  my_char('\n');
  my_str("my_strindex(\"hello\", 'h') = ");
  my_int(my_strindex("hello", 'h'));
  my_char('\n');
  my_str("my_strindex(\"hello\", 'o') = ");
  my_int(my_strindex("hello", 'o'));
  my_char('\n');
  my_str("my_strindex(\"\", 'l') = ");
  my_int(my_strindex("", 'l'));
  my_char('\n');
  my_str("my_strindex(NULL, 'l') = ");
  my_int(my_strindex(NULL, 'l'));
  my_char('\n');
  my_str("my_strindex(\"hello\", 'r') = ");
  my_int(my_strindex("hello", 'r'));
  my_char('\n');

  char str[] = "carlos";
  char str1[] = "hello";
  char str2[] = "a";
  char str3[] = "";
  char str4[] = "BR";

  my_str("\nmy_revstr()\n-----------\n");
  my_str("my_revstr(\"carlos\") = ");
  my_int(my_revstr(str));
  my_char(' ');
  my_str(str);
  my_char('\n');
  my_str("my_revstr(\"hello\") = ");
  my_int(my_revstr(str1));
  my_char(' ');
  my_str(str1);
  my_char('\n');
  my_str("my_revstr(\"a\") = ");
  my_int(my_revstr(str2));
  my_char(' ');
  my_str(str2);
  my_char('\n');
  my_str("my_revstr(\"\") = ");
  my_int(my_revstr(str3));
  my_char(' ');
  my_str(str3);
  my_char('\n');
  my_str("my_revstr(\"BR\") = ");
  my_int(my_revstr(str4));
  my_char(' ');
  my_str(str4);
  my_char('\n');
  my_str("my_revstr(NULL) = ");
  my_int(my_revstr(NULL));
  my_char(' ');
  my_str(NULL);
  my_char('\n');

  my_str("\nmy_strrindex()\n--------------\n");
  my_str("my_strrindex(\"hello\", 'l') = ");
  my_int(my_strrindex("hello", 'l'));
  my_char('\n');
  my_str("my_strrindex(\"hello\", 'h') = ");
  my_int(my_strrindex("hello", 'h'));
  my_char('\n');
  my_str("my_strrindex(\"hello\", 'w') = ");
  my_int(my_strrindex("hello", 'w'));
  my_char('\n');
  my_str("my_strrindex(\"\", 'l') = ");
  my_int(my_strrindex("", 'l'));
  my_char('\n');
  my_str("my_strrindex(NULL, 'l') = ");
  my_int(my_strrindex(NULL, 'l'));
  my_char('\n');
  my_str("my_strrindex(\"hello\", 'o') = ");
  my_int(my_strrindex("hello", 'o'));
  my_char('\n');

  my_str("\nmy_num_base()\n-------------\n");
  my_str("my_num_base(9, \"RTFM\") = ");
  my_num_base(9, "RTFM");
  my_char('\n');
  my_str("my_num_base(-3, \"!\") = ");
  my_num_base(-3, "!");
  my_char('\n');
  my_str("my_num_base(9, \"\") = ");
  my_num_base(9, "");
  my_str("my_num_base(3, NULL) = ");
  my_num_base(3, NULL);
  my_str("my_num_base(6, \"01\") = ");
  my_num_base(6, "01");
  my_char('\n');
  my_str("my_num_base(0, \"hello\") = ");
  my_num_base(0, "hello");
  my_char('\n');
  my_str("my_num_base(8, \"index\") = ");
  my_num_base(8, "index");
  my_char('\n');
  my_str("my_num_base(9, \"0123456789\") = ");
  my_num_base(9, "0123456789");
  my_char('\n');
  my_str("my_num_base(123, \"0123456789\") = ");
  my_num_base(123, "0123456789");
  my_char('\n');*/

  return 0;
}
